package com.mycompany.hibernate.model;
// Generated Jan 30, 2018 9:45:45 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StudentInfo generated by hbm2java
 */
@Entity
@Table(name="student_info"
    ,catalog="student"
)
public class StudentInfo  implements java.io.Serializable {


     private Integer id;
     private String name;

    public StudentInfo() {
    }

    public StudentInfo(String name) {
       this.name = name;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


